"""Normal-memory vocabulary for the lossy v0.2 packer.

The base entries are grouped for review. Common ``the ...`` and ``user ...``
forms are expanded into explicit runtime mappings, giving the packer more than
300 stable phrase mappings without maintaining separate parsing branches.
"""

from __future__ import annotations


WordPair = tuple[str, str]


CATEGORY_MAPPINGS: dict[str, tuple[WordPair, ...]] = {
    "USER_PREFS": (
        ("low-token mode", "tok=low"),
        ("low token mode", "tok=low"),
        ("short answers", "ans=short"),
        ("concise answers", "ans=concise"),
        ("direct answers", "ans=direct"),
        ("detailed answers", "ans=detail"),
        ("no fluff", "no=fluff"),
        ("one-box copy paste commands", "cmd=1box"),
        ("copy and paste commands", "cmd=cp"),
        ("copy paste commands", "cmd=cp"),
        ("copy paste", "cp"),
        ("sources only when needed", "src=needed"),
        ("ask before changing", "ask.before.change"),
        ("do not assume", "no.assume"),
        ("verify first", "verify"),
        ("plain language", "lang=plain"),
        ("step by step", "steps"),
        ("minimal formatting", "fmt=min"),
    ),
    "COMM_STYLE": (
        ("communication style", "comm.style"),
        ("friendly tone", "tone=friendly"),
        ("professional tone", "tone=pro"),
        ("casual tone", "tone=casual"),
        ("warm tone", "tone=warm"),
        ("lead with the answer", "answer.first"),
        ("lead with the outcome", "outcome.first"),
        ("avoid jargon", "no.jargon"),
        ("explain technical terms", "explain.terms"),
        ("use bullet points", "bullets"),
        ("avoid long lists", "lists=short"),
        ("keep it brief", "brief"),
        ("be explicit", "explicit"),
        ("ask clarifying questions", "ask.clarify"),
        ("do not repeat", "no.repeat"),
        ("when needed", "if.needed"),
        ("only when necessary", "if.needed"),
        ("preferred response style", "resp.style"),
    ),
    "WORKFLOW": (
        ("workflow", "wf"),
        ("dry-run first", "dry.first"),
        ("dry run first", "dry.first"),
        ("preview first", "prev.first"),
        ("make a backup before editing", "bk.before.edit"),
        ("backups before edits", "bk.before.edit"),
        ("backup before changes", "bk.before.change"),
        ("git checkpoints", "git.ckpt"),
        ("save a checkpoint", "save.ckpt"),
        ("review before applying", "review.before.apply"),
        ("test before applying", "test.before.apply"),
        ("confirm before deleting", "confirm.before.del"),
        ("one step at a time", "stepwise"),
        ("working process", "process"),
        ("quality check", "qa"),
        ("manual review", "review=manual"),
        ("approval required", "approval=req"),
        ("rollback plan", "rollback"),
    ),
    "PROJECTS": (
        ("project", "proj"),
        ("project notes", "proj.notes"),
        ("active project", "proj.active"),
        ("current project", "proj.current"),
        ("AI agent project", "AI.agent.proj"),
        ("local execution", "local.exec"),
        ("execution layer", "exec.layer"),
        ("in development", "dev"),
        ("production ready", "prod.ready"),
        ("proof of concept", "POC"),
        ("minimum viable product", "MVP"),
        ("source repository", "src.repo"),
        ("project directory", "proj.dir"),
        ("project status", "proj.status"),
        ("release version", "release"),
        ("next release", "release.next"),
        ("feature request", "feat.req"),
        ("known issue", "issue.known"),
    ),
    "AGENTS": (
        ("agent", "agent"),
        ("agent behavior", "agent.behavior"),
        ("AI assistant", "AI.asst"),
        ("local agent", "agent.local"),
        ("remote agent", "agent.remote"),
        ("sub-agent", "subagent"),
        ("memory agent", "mem.agent"),
        ("routing agent", "router.agent"),
        ("autonomous mode", "mode=auto"),
        ("manual mode", "mode=manual"),
        ("safe by default", "safe.default"),
        ("needs permission", "perm=req"),
        ("agent should", "agent:"),
        ("agent must", "agent!"),
        ("agent can", "agent.can"),
        ("assistant should", "asst:"),
        ("assistant must", "asst!"),
        ("system prompt", "sys.prompt"),
    ),
    "DEVICES": (
        ("device", "dev"),
        ("device notes", "dev.notes"),
        ("device model", "dev.model"),
        ("Linux laptop", "Linux laptop"),
        ("desktop computer", "desktop"),
        ("mobile phone", "phone"),
        ("smart phone", "phone"),
        ("tablet computer", "tablet"),
        ("home server", "server.home"),
        ("work computer", "computer.work"),
        ("primary device", "dev.primary"),
        ("secondary device", "dev.secondary"),
        ("operating system", "OS"),
        ("host name", "host"),
        ("hostname", "host"),
        ("serial number", "serial"),
        ("IP address", "IP"),
        ("hardware notes", "hw.notes"),
    ),
    "ACCOUNTS": (
        ("account", "acct"),
        ("account notes", "acct.notes"),
        ("email address", "email"),
        ("user name", "user"),
        ("username", "user"),
        ("service account", "svc.acct"),
        ("administrator account", "admin.acct"),
        ("personal account", "acct.personal"),
        ("work account", "acct.work"),
        ("cloud account", "cloud.acct"),
        ("login name", "login"),
        ("authentication", "auth"),
        ("two factor authentication", "2FA"),
        ("multi factor authentication", "MFA"),
        ("password manager", "pw.mgr"),
        ("access token", "access.tok"),
        ("API key", "API.key"),
        ("subscription", "sub"),
    ),
    "PATHS": (
        ("path", "path"),
        ("important paths", "paths"),
        ("file path", "f.path"),
        ("directory path", "dir.path"),
        ("repository path", "repo.path"),
        ("home directory", "home.dir"),
        ("working directory", "work.dir"),
        ("configuration directory", "cfg.dir"),
        ("data directory", "data.dir"),
        ("backup directory", "bk.dir"),
        ("temporary directory", "tmp.dir"),
        ("log directory", "log.dir"),
        ("input file", "in.f"),
        ("output file", "out.f"),
        ("memory file", "mem.f"),
        ("configuration file", "cfg.f"),
        ("environment file", "env.f"),
        ("project root", "proj.root"),
    ),
    "CODING": (
        ("configuration", "cfg"),
        ("repository", "repo"),
        ("directory", "dir"),
        ("source code", "src"),
        ("command line", "CLI"),
        ("command line interface", "CLI"),
        ("user interface", "UI"),
        ("application", "app"),
        ("development environment", "dev.env"),
        ("code editor", "editor"),
        ("test suite", "tests"),
        ("unit tests", "unit.tests"),
        ("integration tests", "int.tests"),
        ("bug fix", "fix"),
        ("code review", "review"),
        ("version control", "VCS"),
        ("dependency", "dep"),
        ("documentation", "docs"),
    ),
    "SECURITY_BASIC": (
        ("security", "sec"),
        ("password rule", "pw.rule"),
        ("do not expose", "no.expose"),
        ("keep private", "private"),
        ("sensitive information", "sensitive"),
        ("personal information", "PII"),
        ("secret value", "secret"),
        ("read only", "RO"),
        ("write access", "RW"),
        ("access control", "ACL"),
        ("permission check", "perm.check"),
        ("ask for permission", "ask.perm"),
        ("do not overwrite", "no.owr"),
        ("do not delete", "no.del"),
        ("safe mode", "safe"),
        ("risk warning", "risk"),
        ("recovery key", "recovery.key"),
        ("encrypted storage", "storage.enc"),
    ),
    "STATUS": (
        ("status", "status"),
        ("current status", "status"),
        ("currently active", "active"),
        ("currently working", "working"),
        ("in progress", "WIP"),
        ("not started", "new"),
        ("completed", "done"),
        ("finished", "done"),
        ("blocked", "blocked"),
        ("pending", "pend"),
        ("approved", "ok"),
        ("rejected", "no"),
        ("ready for review", "review.ready"),
        ("waiting for input", "wait.input"),
        ("waiting for approval", "wait.ok"),
        ("working correctly", "works"),
        ("is live", "live"),
        ("is available", "avail"),
    ),
    "TASKS": (
        ("task", "task"),
        ("open task", "task.open"),
        ("open tasks", "tasks.open"),
        ("next action", "next"),
        ("next step", "next"),
        ("to do", "todo"),
        ("todo item", "todo"),
        ("needs review", "needs.review"),
        ("needs testing", "needs.test"),
        ("needs update", "needs.update"),
        ("follow up", "followup"),
        ("later task", "later"),
        ("high priority", "prio=high"),
        ("low priority", "prio=low"),
        ("due date", "due"),
        ("assigned to", "owner="),
        ("task owner", "owner"),
        ("acceptance criteria", "accept"),
    ),
    "MEMORY": (
        ("memory", "mem"),
        ("memory notes", "mem.notes"),
        ("remember that", ""),
        ("persistent memory", "pmem"),
        ("session history", "sess.hist"),
        ("injected context", "inj.ctx"),
        ("memory injection budget", "mem.inj.budget"),
        ("token budget", "tok.budget"),
        ("long term memory", "lt.mem"),
        ("short term memory", "st.mem"),
        ("memory record", "mem.rec"),
        ("memory file", "mem.f"),
        ("context window", "ctx.win"),
        ("conversation context", "conv.ctx"),
        ("session notes", "sess.notes"),
        ("user profile", "user.profile"),
        ("standing instruction", "rule"),
        ("repeated status note", "status.repeat"),
    ),
}


def _build_wordlist() -> tuple[WordPair, ...]:
    mappings: list[WordPair] = []
    seen: set[str] = set()
    for pairs in CATEGORY_MAPPINGS.values():
        for phrase, shorthand in pairs:
            variants = [phrase]
            if " " in phrase and not phrase.startswith(("the ", "user ")):
                variants.extend((f"the {phrase}", f"user {phrase}"))
            for variant in variants:
                key = variant.casefold()
                if key not in seen:
                    seen.add(key)
                    mappings.append((variant, shorthand))
    return tuple(mappings)


WORDLIST = _build_wordlist()

if len(WORDLIST) < 300:  # Guard the public v0.2 vocabulary contract.
    raise RuntimeError("AIsteno v0.2 wordlist must contain at least 300 mappings")
